repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: forbid-submodules

## GOLANG
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.2
  hooks:
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - --args=-write=false
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
        - --hook-config=--use-standard-markers=true     # Boolean. Defaults to true (v1.93+),
## GIT
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []

## SECURITY
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.19.2
  hooks:
    - id: gitleaks
